#!/usr/bin/env python3
"""Populate the SKILLS block in CLAUDE.md and AGENTS.md from skills/ frontmatter.

  python scripts/gen-bootstrap.py          # rewrite the SKILLS:BEGIN..END block
  python scripts/gen-bootstrap.py --check  # exit 1 if regeneration would change anything

Idempotent: re-running with no skill changes produces an identical block.
Adding a skill needs no manual edit here -- the block regenerates from skills/.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKILLS = os.path.join(ROOT, "skills")
BEGIN = "<!-- SKILLS:BEGIN (generated by scripts/gen-bootstrap) -->"
END = "<!-- SKILLS:END -->"


def parse_fm(text):
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    fm = {}
    if m:
        for line in m.group(1).splitlines():
            if ":" in line:
                k, _, v = line.partition(":")
                v = v.strip()
                if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
                    v = v[1:-1]
                fm[k.strip()] = v.strip()
    return fm


def skill_lines():
    rows = []
    for name in sorted(os.listdir(SKILLS)):
        sk = os.path.join(SKILLS, name, "SKILL.md")
        if name == "_shared" or not os.path.isfile(sk):
            continue
        with open(sk, encoding="utf-8") as f:
            fm = parse_fm(f.read())
        rows.append(f"- **{name}** — {fm.get('description', '')}")
    return rows


def block():
    return "\n".join([BEGIN, "", f"## Skills ({len(skill_lines())})", "", *skill_lines(), "", END])


def apply(path, check):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block(), text, flags=re.S)
    if check:
        return new == text
    if new != text:
        with open(path, "w", encoding="utf-8") as f:
            f.write(new)
    return True


def main():
    check = "--check" in sys.argv
    ok = True
    for fn in ("CLAUDE.md", "AGENTS.md"):
        p = os.path.join(ROOT, fn)
        if not os.path.isfile(p):
            continue
        res = apply(p, check)
        if check and not res:
            ok = False
            print(f"STALE: {fn} SKILLS block out of date")
        elif not check:
            print(f"Updated {fn}")
    if check and not ok:
        sys.exit(1)
    if check:
        print("bootstrap blocks up to date")


if __name__ == "__main__":
    main()
