#!/usr/bin/env python3
"""Populate the SKILLS block in CLAUDE.md and AGENTS.md from skills/ frontmatter.

  python3 scripts/gen-bootstrap.py              # rewrite the SKILLS:BEGIN..END block
  python3 scripts/gen-bootstrap.py --check      # exit 1 if regeneration would change anything
  python3 scripts/gen-bootstrap.py --root DIR   # operate on DIR instead of the repo root

Exits 1 in both modes when CLAUDE.md or AGENTS.md is absent ("MISSING: <file>") or has no
SKILLS:BEGIN..END markers ("MISSING MARKERS: <file>"), so a file it cannot regenerate is
never skipped silently.

Idempotent: re-running with no skill changes produces an identical block.
Adding a skill needs no manual edit here -- the block regenerates from skills/.
"""
import argparse
import os
import re
import sys

DEFAULT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGETS = ("CLAUDE.md", "AGENTS.md")
BEGIN = "<!-- SKILLS:BEGIN (generated by scripts/gen-bootstrap) -->"
END = "<!-- SKILLS:END -->"
BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)


def parse_fm(text):
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    fm = {}
    if m:
        for line in m.group(1).splitlines():
            if ":" in line:
                k, _, v = line.partition(":")
                v = v.strip()
                if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
                    v = v[1:-1]
                fm[k.strip()] = v.strip()
    return fm


def skill_lines(root):
    skills = os.path.join(root, "skills")
    rows = []
    for name in sorted(os.listdir(skills)):
        sk = os.path.join(skills, name, "SKILL.md")
        if name == "_shared" or not os.path.isfile(sk):
            continue
        with open(sk, encoding="utf-8") as f:
            fm = parse_fm(f.read())
        rows.append(f"- **{name}** — {fm.get('description', '')}")
    return rows


def block(root):
    rows = skill_lines(root)
    return "\n".join([BEGIN, "", f"## Skills ({len(rows)})", "", *rows, "", END])


def main(argv=None):
    ap = argparse.ArgumentParser(description="Populate the SKILLS block in CLAUDE.md and AGENTS.md.")
    ap.add_argument("--check", action="store_true", help="exit 1 if regeneration would change anything")
    ap.add_argument("--root", default=DEFAULT_ROOT,
                    help="repo root to operate on (default: parent of scripts/)")
    args = ap.parse_args(argv)

    generated = block(args.root)
    ok = True
    for fn in TARGETS:
        path = os.path.join(args.root, fn)
        if not os.path.isfile(path):
            print(f"MISSING: {fn}")
            ok = False
            continue
        with open(path, encoding="utf-8") as f:
            text = f.read()
        if not BLOCK.search(text):
            print(f"MISSING MARKERS: {fn}")
            ok = False
            continue
        new = BLOCK.sub(generated, text)
        if args.check:
            if new != text:
                print(f"STALE: {fn} SKILLS block out of date")
                ok = False
        else:
            if new != text:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(new)
            print(f"Updated {fn}")
    if args.check and ok:
        print("bootstrap blocks up to date")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
