#!/usr/bin/env python3
"""Generate CATALOG.md from skills/ and lint skill frontmatter.

  python scripts/gen-catalog.py          # regenerate CATALOG.md
  python scripts/gen-catalog.py --check  # lint only; exit 1 on any violation

Lints (constellation house rules):
  - every skill has name + description frontmatter
  - description is triggering-conditions only (starts with "Use when"); no workflow summary
  - no section-sign character anywhere in any tracked markdown
Adding a skill = drop skills/<name>/SKILL.md; the catalog auto-registers it. No manifest edit.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKILLS = os.path.join(ROOT, "skills")
SECTION_SIGN = "§"


def parse_frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            v = v.strip()
            if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
                v = v[1:-1]
            fm[k.strip()] = v.strip()
    return fm


def discover():
    out = []
    for name in sorted(os.listdir(SKILLS)):
        d = os.path.join(SKILLS, name)
        sk = os.path.join(d, "SKILL.md")
        if name == "_shared" or not os.path.isfile(sk):
            continue
        with open(sk, encoding="utf-8") as f:
            fm = parse_frontmatter(f.read())
        out.append((name, fm.get("name", name), fm.get("description", "")))
    return out


def lint(skills):
    errs = []
    for name, sk_name, desc in skills:
        if not desc:
            errs.append(f"{name}: missing description")
        elif not desc.lower().startswith("use when"):
            errs.append(f"{name}: description must start with 'Use when' (triggering conditions only)")
        if sk_name != name:
            errs.append(f"{name}: frontmatter name '{sk_name}' != directory name")
    # section-sign scan across tracked markdown
    for dirpath, _, files in os.walk(ROOT):
        if "/.git" in dirpath:
            continue
        for fn in files:
            if fn.endswith(".md"):
                p = os.path.join(dirpath, fn)
                with open(p, encoding="utf-8", errors="ignore") as f:
                    if SECTION_SIGN in f.read():
                        errs.append(f"{os.path.relpath(p, ROOT)}: contains the section-sign character")
    return errs


def render(skills):
    lines = [
        "# Constellation Catalog",
        "",
        "Generated by `scripts/gen-catalog.py` from `skills/`. Do not edit by hand.",
        "",
        f"{len(skills)} skills.",
        "",
        "| Skill | Triggers on |",
        "|---|---|",
    ]
    for name, _, desc in skills:
        lines.append(f"| `{name}` | {desc} |")
    lines.append("")
    return "\n".join(lines)


def main():
    skills = discover()
    check = "--check" in sys.argv
    errs = lint(skills)
    if check:
        if errs:
            print("LINT FAILED:")
            for e in errs:
                print("  -", e)
            sys.exit(1)
        print(f"LINT OK ({len(skills)} skills)")
        return
    with open(os.path.join(ROOT, "CATALOG.md"), "w", encoding="utf-8") as f:
        f.write(render(skills))
    print(f"Wrote CATALOG.md ({len(skills)} skills)")
    if errs:
        print("WARNINGS:")
        for e in errs:
            print("  -", e)


if __name__ == "__main__":
    main()
