"""Tests for scripts/gen-bootstrap.py, driven through the real CLI on temp trees.

Each test builds a small repo layout under tmp_path and runs the script with
--root, so no test reads or writes the real repository.

  PYTHONDONTWRITEBYTECODE=1 python3 -m pytest -q -p no:cacheprovider scripts/test_gen_bootstrap.py
"""
import subprocess
import sys
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parent / "gen-bootstrap.py"
BEGIN = "<!-- SKILLS:BEGIN (generated by scripts/gen-bootstrap) -->"
END = "<!-- SKILLS:END -->"
TARGETS = ("CLAUDE.md", "AGENTS.md")
UP_TO_DATE = "bootstrap blocks up to date"


def run(root, *args):
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--root", str(root), *args],
        capture_output=True,
        text=True,
    )


def write_skill(root, name, description):
    d = root / "skills" / name
    d.mkdir(parents=True, exist_ok=True)
    (d / "SKILL.md").write_text(
        f"---\nname: {name}\ndescription: {description}\n---\n\n# {name}\n", encoding="utf-8"
    )


def make_tree(tmp_path):
    """One skill and both target files, each holding an empty SKILLS block that a write run fills."""
    write_skill(tmp_path, "alpha", "Use when testing the bootstrap generator")
    for fn in TARGETS:
        (tmp_path / fn).write_text(
            f"# {fn}\n\nIntro line.\n\n{BEGIN}\n{END}\n\nOutro line.\n", encoding="utf-8"
        )
    proc = run(tmp_path)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    return tmp_path


def test_check_passes_on_fresh_tree(tmp_path):
    root = make_tree(tmp_path)
    text = (root / "CLAUDE.md").read_text(encoding="utf-8")
    assert "- **alpha** — Use when testing the bootstrap generator" in text
    proc = run(root, "--check")
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert proc.stdout.splitlines() == [UP_TO_DATE]


def test_bootstrap_missing_markers(tmp_path):
    root = make_tree(tmp_path)
    (root / "CLAUDE.md").write_text("# CLAUDE.md\n\nNo skills block here.\n", encoding="utf-8")
    proc = run(root, "--check")
    assert proc.returncode == 1, proc.stdout + proc.stderr
    assert proc.stdout.splitlines() == ["MISSING MARKERS: CLAUDE.md"]


def test_bootstrap_write_mode_missing_markers(tmp_path):
    root = make_tree(tmp_path)
    original = "# CLAUDE.md\n\nNo skills block here.\n"
    (root / "CLAUDE.md").write_text(original, encoding="utf-8")
    proc = run(root)
    assert proc.returncode == 1, proc.stdout + proc.stderr
    assert "MISSING MARKERS: CLAUDE.md" in proc.stdout.splitlines()
    assert (root / "CLAUDE.md").read_text(encoding="utf-8") == original


def test_bootstrap_missing_file(tmp_path):
    root = make_tree(tmp_path)
    (root / "AGENTS.md").unlink()
    for args in (("--check",), ()):
        proc = run(root, *args)
        assert proc.returncode == 1, proc.stdout + proc.stderr
        assert "MISSING: AGENTS.md" in proc.stdout.splitlines()
        assert not (root / "AGENTS.md").exists()


@pytest.mark.parametrize(
    "description",
    [
        r"Use when a path like a\nb or a tab like a\tb appears",
        r"Use when a pattern like \d+ appears",
        r"Use when \n, \t and \d all appear",
    ],
    ids=["newline-tab", "bad-escape", "combined"],
)
def test_bootstrap_backslash_description_written_verbatim(tmp_path, description):
    """A backslash in a description must reach CLAUDE.md as typed.

    The generated block was once handed to re.sub as a replacement template, so a literal
    backslash-n became a real newline (splitting the bullet, and --check then agreed with the
    corrupted text) and backslash-d crashed with re.error.
    """
    root = make_tree(tmp_path)
    write_skill(root, "alpha", description)
    bullet = f"- **alpha** — {description}"

    proc = run(root)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    for fn in TARGETS:
        lines = (root / fn).read_text(encoding="utf-8").splitlines()
        assert bullet in lines
        assert not any("\t" in line for line in lines)

    proc = run(root, "--check")
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert proc.stdout.splitlines() == [UP_TO_DATE]


def test_bootstrap_stale_then_regenerate(tmp_path):
    root = make_tree(tmp_path)
    write_skill(root, "alpha", "Use when the description changes")

    proc = run(root, "--check")
    assert proc.returncode == 1, proc.stdout + proc.stderr
    assert proc.stdout.splitlines() == [
        "STALE: CLAUDE.md SKILLS block out of date",
        "STALE: AGENTS.md SKILLS block out of date",
    ]

    proc = run(root)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    for fn in TARGETS:
        text = (root / fn).read_text(encoding="utf-8")
        assert "- **alpha** — Use when the description changes" in text
        assert text.startswith(f"# {fn}\n\nIntro line.\n\n{BEGIN}\n")
        assert text.endswith(f"{END}\n\nOutro line.\n")

    proc = run(root, "--check")
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert proc.stdout.splitlines() == [UP_TO_DATE]
